# overrides for local deployment
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
services:
  shelf-reading:
    build:
      context: ../folio-offline-shelf-reading
    volumes:
      - ../folio-offline-shelf-reading:/app
  folio-shelving-order:
    build:
      context: ../folio-shelving-order
  rollout:
    profiles: [donotstart]
  traefik:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
  gate-counts:
    build:
      context: ../ole-gate-count
  mariadb:
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 172.20.0.10
