---
networks:
  default:

services:
  shelf-reading:
    image: ghcr.io/lehigh-university-libraries/folio-offline-shelf-reading:main
    environment:
        SCRIPT_NAME: /shelf-reading
    healthcheck:
      start_period: 1s
  sentence-transformer:
    image: ghcr.io/lehigh-university-libraries/sentence-transformer:main
    healthcheck:
      start_period: 1s
  rollout:
    image: us-docker.pkg.dev/lehigh-lts-images/internal/rollout:main
    restart: unless-stopped
    volumes:
      - ./:/opt/linderman
      - /root/.docker:/root/.docker:ro
      - /root/.ssh:/root/.ssh
      - ./scripts/maintenance/rollout.sh:/rollout.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JWKS_URI: "https://token.actions.githubusercontent.com/.well-known/jwks"
      JWT_AUD: "https://github.com/lehigh-university-libraries"
      ROLLOUT_LOCK_FILE: /opt/linderman/rollout.lock
      HOSTNAME: ${HOSTNAME}
      DOMAIN: localhost
    healthcheck:
      start_period: 1s
  traefik:
    image: traefik:v3.4.0@sha256:4cf907247939b5d20bf4eff73abd21cb413c339600dde76dbc94a874b2578a27
    restart: always
    command: >-
      --api.insecure=true
      --api.dashboard=true
      --api.debug=true
      --ping=true
      --entryPoints.http.address=:80
      --entryPoints.https.address=:443
      --entryPoints.https.forwardedHeaders.trustedIPs=128.180.1.79/32,128.180.1.80/32,128.180.6.212/32,128.180.6.203/32,172.0.0.0/8
      --entryPoints.https.transport.respondingTimeouts.readTimeout=3600
      --providers.file.filename=/etc/traefik/config.yaml
      --providers.file.watch=true
      --providers.docker=true
      --providers.docker.network=default
      --providers.docker.exposedByDefault=false
    environment:
      DOMAIN: localhost
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/ssl/traefik:Z,ro
      - ./conf/traefik/config.tmpl:/etc/traefik/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:z
    healthcheck:
      test: traefik healthcheck --ping
      start_period: 5s
    networks:
      default:
        aliases:
          - localhost
